services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - adventure_works_postgres_db:/var/lib/postgresql
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

#  backend:
#    image: experimentalsoftware/spring-adventures:backend-latest
#    ports:
#      - "8000:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/Adventureworks

volumes:
  adventure_works_postgres_db:
